### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by danielribeiro** [nooperation/d2es-stuff#2]
@nooperation Is this project abandoned?

I was looking into getting this used on an old mod, but [these kind of messages](https://github.com/nooperation/d2es-stuff/blob/7ee519c0682016a97262d3c08f6adc95d2571e2e/D2Hackit/Core/Inventory.cpp#L254) are not helpful for mods that add tons of items to the item tables.

If the project is abandoned, please disregard this. I know it can be a nuisance to get messages on 8+ year old projects.

Cheers,
- Daniel

**Comment by nooperation** [comment]
Sorry, yeah this was abandoned long long ago. I'm not sure what happened to the original d2hackit source code, but this is just a modified fork of it for Eastern Sun 300r6 on Diablo 1.10

It actually looks like the original author now has a Github project with the original code in it here: https://github.com/thohell/D2HackIt though it looks like that might be an even earlier d2hackit version

**Comment by danielribeiro** [comment]
Ok, thanks for the reply.
